# Generated by Django 5.1.7 on 2025-03-22 09:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='advertisement_image'),
        ),
    ]
