# Generated by Django 5.1.7 on 2025-03-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisementimage_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
