# Generated by Django 5.1.7 on 2025-05-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisementimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['id']},
        ),
    ]
