# Generated by Django 5.1.7 on 2025-03-22 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_favourite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
